### ISSUE TITLE
animate individaul elements...

### ISSUE THREAD

**Issue by jackmachison** [smashingboxes/OwlCarousel2#925]
Hi,

I used owl.carousel 2 for my website and it's fantastic.
Just a question - can I use "animateOut" and "animateIn", for a individaul elements from item block - like inner title and text?
http://screencast.com/t/tZb085uNZK
initially, blue block should be hidden...

kind regrads
Jack

**Comment by NPanayotov** [comment]
The animateOut and animateIn are only for the sliding animations if you want to animate items inside the slides you can add a class to the "active" class of the slide to animate them.

For example

```CSS
.slide-content { opacity: 0; visibility: hidden; transition: opacity .3s, visiblity .3s; (+ the vendor prefixes)  }
.active .slide-contnet { opacity: 1; visiblity: visible; } 

``` 

This should fadein the block
