### ISSUE TITLE
with loop css3-selectors won't work

### ISSUE THREAD

**Issue by tangente** [smashingboxes/OwlCarousel2#949]
using owl.carousel 2.0.0-beta4
example:

i have 4 items and a responsive break like:
```javascript
responsive: {
    568: {
        items: 2,
        nav: true,
        loop: true
      }
} 
```
and i would like to add the first ACTIVE item padding-right 12px and the second ACTIVE item padding-left:12px;
css:
```css
.owl-carousel .owl-item.active:nth-of-type(1) {
    padding-right:12px;
}
.owl-carousel .owl-item.active:nth-of-type(2) {
    padding-left: 12px;
}
```
that doesn't work.

If i switch the loop option to false, than it works! (maybe it has to do with that cloned owl-items? they don't have active class but I don't know)

otherwise, if a define (with loop:true) my css without :nth-of-type selector than the css works too but not as I want (first active item right padding, second active padding-left)
