### ISSUE TITLE
Strange behavior with custom animation

### ISSUE THREAD

**Issue by mrswoop** [smashingboxes/OwlCarousel2#976]
I have created a simple custom animation (a kenburns effect) following the example from animate.css. Here is the animation in total:

```css
.myMove {
  -webkit-animation: myMove;
  animation: myMove;
}

@keyframes myMove {
  0% {
    transform: scale(1.0, 1.0);
    transform-origin: 50% 50%;
  }
  100% {
    transform: scale(1.3, 1.3);
    transform-origin: 50% 0%;
  }
}

@-webkit-keyframes myMove {
  0% {
    transform: scale(1.0, 1.0);
    transform-origin: 50% 50%;
  }
  100% {
    transform: scale(1.3, 1.3);
    transform-origin: 50% 0%;
  }
}
```

On my own website, this is working except for one strange behavior. The last slide only displays for the duration of the autoPlayTimeout (2s), then the first slide is displayed for the duration of the effect (6s), then the first slide continues displaying as it should, 2s still followed by 6s effect.

I tried putting up a codepen of this issue, but it behaves even more strangely. I linked the proper version of jQuery that I am using (1.9.1) and I linked to the owl files used on the owl demo page for animation (`http://owlcarousel.owlgraphic.com/demos/animate.html`).

The codepen is [here] (http://codepen.io/mrswoop/pen/ZGwvbw).

I would be happy to provide any additional information or assistance. I have really been enjoying the Owl Carousel and love to be able to aid with some testing help. Everything I have done is working except for the use of this transition on one slider.
